// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorshipProgramPlannerApp.Data;

#nullable disable

namespace WorshipProgramPlannerApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250202205509_AutoIncrementingWorshipId")]
    partial class AutoIncrementingWorshipId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorshipProgramPlannerApp.Models.Worship", b =>
                {
                    b.Property<int>("WorshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorshipId"));

                    b.Property<DateTime>("WorshipDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorshipName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorshipId");

                    b.ToTable("Worships");
                });

            modelBuilder.Entity("WorshipProgramPlannerApp.Models.WorshipProgram", b =>
                {
                    b.Property<int>("WorshipProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorshipProgramId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoetryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SongName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorshipId")
                        .HasColumnType("int");

                    b.HasKey("WorshipProgramId");

                    b.HasIndex("WorshipId");

                    b.ToTable("WorshipPrograms");
                });

            modelBuilder.Entity("WorshipProgramPlannerApp.Models.WorshipProgram", b =>
                {
                    b.HasOne("WorshipProgramPlannerApp.Models.Worship", "Worship")
                        .WithMany("WorshipPrograms")
                        .HasForeignKey("WorshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worship");
                });

            modelBuilder.Entity("WorshipProgramPlannerApp.Models.Worship", b =>
                {
                    b.Navigation("WorshipPrograms");
                });
#pragma warning restore 612, 618
        }
    }
}
